cache: pip
dist: bionic
language: python
sudo: required

python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"

allow_failure:
    - python: "3.9"

install:
    - pip install -r requirements.txt
    - pip freeze

before_script:
    - make prepare
    - make install-db

script:
    - make test-ci

after_success:
    - make upload-coverage

deploy:
    provider: script
    script: make upload-pypi
    on:
        python: 3.9
        tags: true

notifications:
    email: false
